[context.production]
  publish = "dist/"
  command = "npm run build"

[context.noncontributing] 
  command = "echo 'noncontributing'"
  base = "noncontributing"
  environment = { MAPBOX_TOKEN = "mapbox" }
